---
title: 'Data 621 HW1: MLB Regression Project'
author: "Mohamed Hassan-El Serafi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(tidyverse)
library(gtExtras)
library(vtable)
library(kableExtra)
library(reactable)
library(GGally)
library(corrplot)
library(corrr)
library(caret)
library(leaps)
library(MASS)
library(mice)
library(dlookr)
library(VIM)
```


## Data Exploration



```{r}
mlb_df <- read.csv("https://raw.githubusercontent.com/moham6839/Data_621_HW1/main/moneyball-evaluation-data.csv")
```

```{r}
mlb_training <- read.csv("https://raw.githubusercontent.com/moham6839/Data_621_HW1/main/moneyball-training-data.csv")
```


```{r}
glimpse(mlb_df)
```







```{r}
reactable(mlb_df)
```

```{r}
reactable(mlb_training)
```


```{r}
summary(mlb_training)
```




```{r}
mlb_training %>%
  gather(variable, value, TARGET_WINS:TEAM_FIELDING_DP) %>%
  ggplot(., aes(value)) + 
  geom_density(fill = "blue", color="blue") + 
  facet_wrap(~variable, scales ="free", ncol = 4) +
  labs(x = element_blank(), y = element_blank())
```


```{r}
ggplot(gather(mlb_training), aes(value)) + 
    geom_histogram(bins = 8) + 
    facet_wrap(~key, scales = 'free_x')
```




```{r}
positive_impact <- mlb_training %>%
  dplyr::select(TARGET_WINS, TEAM_BATTING_H, TEAM_BATTING_2B, TEAM_BATTING_3B, TEAM_BATTING_HR, 
         TEAM_BATTING_BB, TEAM_BATTING_HBP, TEAM_BASERUN_SB, TEAM_FIELDING_DP, TEAM_PITCHING_SO)
```


```{r}
negative_impact <- mlb_training %>%
  dplyr::select(TARGET_WINS, TEAM_BATTING_SO, TEAM_PITCHING_H, TEAM_PITCHING_HR, 
                TEAM_PITCHING_BB, TEAM_BASERUN_CS, TEAM_FIELDING_E)
```







```{r}
mlb_training %>% 
  correlate() %>% 
  focus(TARGET_WINS) %>%
  arrange(desc(TARGET_WINS))
```

```{r}
mlb_training %>%
  gather(-TARGET_WINS, key = "var", value = "value") %>% 
  ggplot(aes(x = value, y = TARGET_WINS)) +
    facet_wrap(~ var, scales = "free") +
    geom_point(fill = "blue", color="blue") +
    geom_smooth(method = "lm", se = FALSE, color = "black") + 
  labs(x = element_blank(), y = "Wins")
```

```{r}
temp <- mlb_training %>% 
  cor(., use = "complete.obs") #%>%
  
temp[lower.tri(temp, diag=TRUE)] <- ""
temp <- temp %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  gather(Variable, Correlation, -rowname) %>%
  filter(Variable != rowname) %>%
  filter(Correlation != "") %>%
  mutate(Correlation = as.numeric(Correlation)) %>%
  rename(` Variable` = rowname) %>%
  arrange(desc(abs(Correlation))) 
```


```{r}
temp %>%
  filter(abs(Correlation) > .5) %>%
  kable() %>%
  kable_styling()
```


```{r}
mlb_training %>% 
  gather(variable, value) %>%
  filter(is.na(value)) %>%
  group_by(variable) %>%
  tally() %>%
  mutate(percent = n / nrow(mlb_training) * 100) %>%
  mutate(percent = paste0(round(percent, ifelse(percent < 10, 1, 0)), "%")) %>%
  arrange(desc(n)) %>%
  rename(`Variable Missing Data` = variable,
         `Number of Records` = n,
         `Share of Total` = percent) %>%
  kable() %>%
  kable_styling()
```







```{r}
na_mlb <- sapply(mlb_training, function(y) sum(length(which(is.na(y))))) %>% as.data.frame() 
colnames(na_mlb) <- "NA_Count"
na_mlb$Variable <- rownames(na_mlb)
na_mlb %>% 
  dplyr::select(Variable, NA_Count) %>% 
  arrange(desc(NA_Count)) %>%
  mutate("Missing_Data_Percentage" = round(NA_Count/nrow(mlb_training),2)*100) %>% 
  #mutate("Missing_Data_Percentage" = paste0(round("Missing_Data_Percentage", ifelse("Missing_Data_Percentage" < 10, 1, 0)), "%")) %>%
  kable(caption="<center>Missing Data Count and Percentage", align = "c") %>% 
  kable_styling(latex_options="scale_down", c("striped", "hover", "condensed", full_width=F))
```







```{r}
imputed_Data <- mice(iris.mis, m=5, maxit = 50, method = 'pmm', seed = 500)
summary(imputed_Data)
```





## Data Preparation


```{r}
new_df$log_win_shares <- log1p(new_df$win_shares)
```







## Model Building

```{r}
mlb_model <- lm(TARGET_WINS ~., data = mlb_training)
# Stepwise regression model
step.model <- stepAIC(mlb_model, direction = "both", 
                      trace = FALSE)
summary(step.model)
```



```{r}
# Set seed for reproducibility
set.seed(123)
# Set up repeated k-fold cross-validation
train.control <- trainControl(method = "cv", number = 10)
# Train the model
step.model <- train(Fertility ~., data = swiss,
                    method = "leapBackward", 
                    tuneGrid = data.frame(nvmax = 1:5),
                    trControl = train.control
                    )
step.model$results
```


```{r}
models <- regsubsets(Fertility ~., data = swiss, nvmax = 5,
                     method = "seqrep")
summary(models)
```





## Model Selection







